---
name: mysql-8_4

services:
  db:
    image: mysql:8.4.5
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306

volumes:
  db-vol:
    name: mysql-8_4
