---
name: mysql-8_4

services:
  db:
    image: mysql:8.4.5
    volumes:
      - db-vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
    networks:
      network:
        ipv4_address: 172.0.0.2

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16
          gateway: 172.0.0.1

volumes:
  db-vol:
    name: mysql-8_4
