---
name: postgres-17_5

services:
  db:
    image: postgres:17.5
    volumes:
      - db-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  db-vol:
    name: postgres-17_5
